### ISSUE TITLE
[documentation] Complete AndrewNG Course 1 : Neural Networks and Deep Learning

### ISSUE THREAD

**Issue by sarrah-basta** [YatharthDedhia/Eklavya-Smart-Stand#2]
You can close this issue once you both finish with the [Course 1 of Deep Learning Specialization by Andrew NG](https://www.coursera.org/learn/neural-networks-deep-learning) and add the notes you make along the way as well! In the comments of this issue, add the [commit id](https://stackoverflow.com/questions/8910271/how-can-i-reference-a-commit-in-an-issue-comment-on-github) prior to closing it.

**Comment by YatharthDedhia** [comment]
Yatharth Commit ID: 05568dbd23789ff8ddd5f53eda5bec08aac497d1
