### ISSUE TITLE
[assignments] AndrewNG Course 1 : Neural Networks and Deep Learning

### ISSUE THREAD

**Issue by sarrah-basta** [YatharthDedhia/Eklavya-Smart-Stand#3]
You can close this issue once you both finish the specified assignments of [Course 1 of Deep Learning Specialization by Andrew NG](https://www.coursera.org/learn/neural-networks-deep-learning) . Reference the relavant [commit id](https://stackoverflow.com/questions/8910271/how-can-i-reference-a-commit-in-an-issue-comment-on-github) in the comments of this issue prior to closing it.

**Comment by YatharthDedhia** [comment]
Yatharth Assignment Commit ID: ca6d4298f23cdf2f260eb72a2610d2f202379231
