### ISSUE TITLE
[documentation] Brush through ESP installations and run Hello World

### ISSUE THREAD

**Issue by sarrah-basta** [YatharthDedhia/Eklavya-Smart-Stand#4]
You can close this issue once you both finish with the [ESP installations](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/index.html) and run the Hello World example . If you make any notes along the way, add them by referencing the [commit id](https://stackoverflow.com/questions/8910271/how-can-i-reference-a-commit-in-an-issue-comment-on-github) In the comments of this issue prior to closing it.

**Comment by YatharthDedhia** [comment]
Yatharth Notes Commit ID: 44a45edbde73b17f3fbf63815d018df23a2c8755
